# #Big Mart Sales Problem

In [61]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [62]:
train=pd.read_csv("C:/Users/LENOVO/Desktop/self project/train.csv")
test =pd.read_csv("C:/Users/LENOVO/Desktop/self project/test.csv")

In [63]:
train['source']='train'
test['source']='test'
df = pd.concat([train, test],ignore_index=True) #combine train &test data
df

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0               FDA15         9.30          Low Fat         0.016047   
1               DRC01         5.92          Regular         0.019278   
2               FDN15        17.50          Low Fat         0.016760   
3               FDX07        19.20          Regular         0.000000   
4               NCD19         8.93          Low Fat         0.000000   
...               ...          ...              ...              ...   
14199           FDB58        10.50          Regular         0.013496   
14200           FDD47         7.60          Regular         0.142991   
14201           NCO17        10.00          Low Fat         0.073529   
14202           FDJ26        15.30          Regular         0.000000   
14203           FDU37         9.50          Regular         0.104720   

                   Item_Type  Item_MRP Outlet_Identifier  \
0                      Dairy  249.8092            OUT049   
1                Soft Drinks   48.2692            OUT018   
2                       Meat  141.6180            OUT049   
3      Fruits and Vegetables  182.0950            OUT010   
4                  Household   53.8614            OUT013   
...                      ...       ...               ...   
14199            Snack Foods  141.3154            OUT046   
14200          Starchy Foods  169.1448            OUT018   
14201     Health and Hygiene  118.7440            OUT045   
14202                 Canned  214.6218            OUT017   
14203                 Canned   79.7960            OUT045   

       Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                           1999      Medium               Tier 1   
1                           2009      Medium               Tier 3   
2                           1999      Medium               Tier 1   
3                           1998         NaN               Tier 3   
4                           1987        High               Tier 3   
...                          ...         ...                  ...   
14199                       1997       Small               Tier 1   
14200                       2009      Medium               Tier 3   
14201                       2002         NaN               Tier 2   
14202                       2007         NaN               Tier 2   
14203                       2002         NaN               Tier 2   

             Outlet_Type  Item_Outlet_Sales source  
0      Supermarket Type1          3735.1380  train  
1      Supermarket Type2           443.4228  train  
2      Supermarket Type1          2097.2700  train  
3          Grocery Store           732.3800  train  
4      Supermarket Type1           994.7052  train  
...                  ...                ...    ...  
14199  Supermarket Type1                NaN   test  
14200  Supermarket Type2                NaN   test  
14201  Supermarket Type1                NaN   test  
14202  Supermarket Type1                NaN   test  
14203  Supermarket Type1                NaN   test  

[14204 rows x 13 columns]

In [64]:
df.describe(percentiles= [.20, .40, .60, .80])

Item_Weight  Item_Visibility      Item_MRP  Outlet_Establishment_Year  \
count  11765.000000     14204.000000  14204.000000               14204.000000   
mean      12.792854         0.065953    141.004977                1997.830681   
std        4.652502         0.051459     62.086938                   8.371664   
min        4.555000         0.000000     31.290000                1985.000000   
20%        7.960000         0.022828     85.142400                1987.000000   
40%       10.895000         0.041886    118.609800                1998.000000   
50%       12.600000         0.054021    142.247000                1999.000000   
60%       14.300000         0.067637    159.026200                2002.000000   
80%       17.700000         0.105626    194.579400                2007.000000   
max       21.350000         0.328391    266.888400                2009.000000   

       Item_Outlet_Sales  
count        8523.000000  
mean         2181.288914  
std          1706.499616  
min            33.290000  
20%           666.465800  
40%          1402.174800  
50%          1794.331000  
60%          2257.328320  
80%          3453.504600  
max         13086.964800

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14204 entries, 0 to 14203
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Identifier            14204 non-null  object 
 1   Item_Weight                11765 non-null  float64
 2   Item_Fat_Content           14204 non-null  object 
 3   Item_Visibility            14204 non-null  float64
 4   Item_Type                  14204 non-null  object 
 5   Item_MRP                   14204 non-null  float64
 6   Outlet_Identifier          14204 non-null  object 
 7   Outlet_Establishment_Year  14204 non-null  int64  
 8   Outlet_Size                10188 non-null  object 
 9   Outlet_Location_Type       14204 non-null  object 
 10  Outlet_Type                14204 non-null  object 
 11  Item_Outlet_Sales          8523 non-null   float64
 12  source                     14204 non-null  object 
dtypes: float64(4), int64(1), object(8)
memory usag

# Fill Missing Values

In [66]:
df.Item_Outlet_Sales = df.Item_Outlet_Sales.fillna(df.Item_Outlet_Sales.mean())

In [67]:
df.Item_Weight=df.Item_Weight.fillna(df.Item_Weight.mean())

In [68]:
df['Outlet_Size'].value_counts()

Medium    4655
Small     3980
High      1553
Name: Outlet_Size, dtype: int64

In [69]:
df.Outlet_Size = df.Outlet_Size.fillna('Medium')

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14204 entries, 0 to 14203
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Identifier            14204 non-null  object 
 1   Item_Weight                14204 non-null  float64
 2   Item_Fat_Content           14204 non-null  object 
 3   Item_Visibility            14204 non-null  float64
 4   Item_Type                  14204 non-null  object 
 5   Item_MRP                   14204 non-null  float64
 6   Outlet_Identifier          14204 non-null  object 
 7   Outlet_Establishment_Year  14204 non-null  int64  
 8   Outlet_Size                14204 non-null  object 
 9   Outlet_Location_Type       14204 non-null  object 
 10  Outlet_Type                14204 non-null  object 
 11  Item_Outlet_Sales          14204 non-null  float64
 12  source                     14204 non-null  object 
dtypes: float64(4), int64(1), object(8)
memory usag

In [71]:
df['Item_Identifier'].value_counts()

FDX46    10
NCV42    10
NCL17    10
FDW01    10
FDK02    10
         ..
FDM50     7
FDL50     7
DRN11     7
FDS22     7
FDO33     7
Name: Item_Identifier, Length: 1559, dtype: int64

In [72]:

df['Item_Identifier'].value_counts()
df['Item_Type_Combined'] = df['Item_Identifier'].apply(lambda x: x[0:2])
df['Item_Type_Combined'] = df['Item_Type_Combined'].map({'FD':'Food',
                                                             'NC':'Non-Consumable',
                                                             'DR':'Drinks'})
df['Item_Type_Combined'].value_counts()

Food              10201
Non-Consumable     2686
Drinks             1317
Name: Item_Type_Combined, dtype: int64

# One-Hot Encoding

In [73]:
#Import library:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le = LabelEncoder()
df['Outlet'] = le.fit_transform(df['Outlet_Identifier'])    #New variable for outlet
var_mod = ['Item_Fat_Content','Outlet_Location_Type','Outlet_Size','Item_Type_Combined','Outlet_Type','Outlet']
le = LabelEncoder()
for i in var_mod:
    df[i] = le.fit_transform(df[i])

In [74]:
df

Item_Identifier  Item_Weight  Item_Fat_Content  Item_Visibility  \
0               FDA15         9.30                 1         0.016047   
1               DRC01         5.92                 2         0.019278   
2               FDN15        17.50                 1         0.016760   
3               FDX07        19.20                 2         0.000000   
4               NCD19         8.93                 1         0.000000   
...               ...          ...               ...              ...   
14199           FDB58        10.50                 2         0.013496   
14200           FDD47         7.60                 2         0.142991   
14201           NCO17        10.00                 1         0.073529   
14202           FDJ26        15.30                 2         0.000000   
14203           FDU37         9.50                 2         0.104720   

                   Item_Type  Item_MRP Outlet_Identifier  \
0                      Dairy  249.8092            OUT049   
1                Soft Drinks   48.2692            OUT018   
2                       Meat  141.6180            OUT049   
3      Fruits and Vegetables  182.0950            OUT010   
4                  Household   53.8614            OUT013   
...                      ...       ...               ...   
14199            Snack Foods  141.3154            OUT046   
14200          Starchy Foods  169.1448            OUT018   
14201     Health and Hygiene  118.7440            OUT045   
14202                 Canned  214.6218            OUT017   
14203                 Canned   79.7960            OUT045   

       Outlet_Establishment_Year  Outlet_Size  Outlet_Location_Type  \
0                           1999            1                     0   
1                           2009            1                     2   
2                           1999            1                     0   
3                           1998            1                     2   
4                           1987            0                     2   
...                          ...          ...                   ...   
14199                       1997            2                     0   
14200                       2009            1                     2   
14201                       2002            1                     1   
14202                       2007            1                     1   
14203                       2002            1                     1   

       Outlet_Type  Item_Outlet_Sales source  Item_Type_Combined  Outlet  
0                1        3735.138000  train                   1       9  
1                2         443.422800  train                   0       3  
2                1        2097.270000  train                   1       9  
3                0         732.380000  train                   1       0  
4                1         994.705200  train                   2       1  
...            ...                ...    ...                 ...     ...  
14199            1        2181.288914   test                   1       8  
14200            2        2181.288914   test                   1       3  
14201            1        2181.288914   test                   2       7  
14202            1        2181.288914   test                   1       2  
14203            1        2181.288914   test                   1       7  

[14204 rows x 15 columns]

In [75]:
df = pd.get_dummies(df, columns=['Item_Fat_Content','Outlet_Location_Type','Outlet_Size','Outlet_Type','Item_Type_Combined','Outlet'])

In [76]:
df

Item_Identifier  Item_Weight  Item_Visibility              Item_Type  \
0               FDA15         9.30         0.016047                  Dairy   
1               DRC01         5.92         0.019278            Soft Drinks   
2               FDN15        17.50         0.016760                   Meat   
3               FDX07        19.20         0.000000  Fruits and Vegetables   
4               NCD19         8.93         0.000000              Household   
...               ...          ...              ...                    ...   
14199           FDB58        10.50         0.013496            Snack Foods   
14200           FDD47         7.60         0.142991          Starchy Foods   
14201           NCO17        10.00         0.073529     Health and Hygiene   
14202           FDJ26        15.30         0.000000                 Canned   
14203           FDU37         9.50         0.104720                 Canned   

       Item_MRP Outlet_Identifier  Outlet_Establishment_Year  \
0      249.8092            OUT049                       1999   
1       48.2692            OUT018                       2009   
2      141.6180            OUT049                       1999   
3      182.0950            OUT010                       1998   
4       53.8614            OUT013                       1987   
...         ...               ...                        ...   
14199  141.3154            OUT046                       1997   
14200  169.1448            OUT018                       2009   
14201  118.7440            OUT045                       2002   
14202  214.6218            OUT017                       2007   
14203   79.7960            OUT045                       2002   

       Item_Outlet_Sales source  Item_Fat_Content_0  ...  Outlet_0  Outlet_1  \
0            3735.138000  train                   0  ...         0         0   
1             443.422800  train                   0  ...         0         0   
2            2097.270000  train                   0  ...         0         0   
3             732.380000  train                   0  ...         1         0   
4             994.705200  train                   0  ...         0         1   
...                  ...    ...                 ...  ...       ...       ...   
14199        2181.288914   test                   0  ...         0         0   
14200        2181.288914   test                   0  ...         0         0   
14201        2181.288914   test                   0  ...         0         0   
14202        2181.288914   test                   0  ...         0         0   
14203        2181.288914   test                   0  ...         0         0   

       Outlet_2  Outlet_3  Outlet_4  Outlet_5  Outlet_6  Outlet_7  Outlet_8  \
0             0         0         0         0         0         0         0   
1             0         1         0         0         0         0         0   
2             0         0         0         0         0         0         0   
3             0         0         0         0         0         0         0   
4             0         0         0         0         0         0         0   
...         ...       ...       ...       ...       ...       ...       ...   
14199         0         0         0         0         0         0         1   
14200         0         1         0         0         0         0         0   
14201         0         0         0         0         0         1         0   
14202         1         0         0         0         0         0         0   
14203         0         0         0         0         0         1         0   

       Outlet_9  
0             1  
1             0  
2             1  
3             0  
4             0  
...         ...  
14199         0  
14200         0  
14201         0  
14202         0  
14203         0  

[14204 rows x 37 columns]

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14204 entries, 0 to 14203
Data columns (total 37 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Identifier            14204 non-null  object 
 1   Item_Weight                14204 non-null  float64
 2   Item_Visibility            14204 non-null  float64
 3   Item_Type                  14204 non-null  object 
 4   Item_MRP                   14204 non-null  float64
 5   Outlet_Identifier          14204 non-null  object 
 6   Outlet_Establishment_Year  14204 non-null  int64  
 7   Item_Outlet_Sales          14204 non-null  float64
 8   source                     14204 non-null  object 
 9   Item_Fat_Content_0         14204 non-null  uint8  
 10  Item_Fat_Content_1         14204 non-null  uint8  
 11  Item_Fat_Content_2         14204 non-null  uint8  
 12  Item_Fat_Content_3         14204 non-null  uint8  
 13  Item_Fat_Content_4         14204 non-null  uin

# Export Data

In [78]:
import warnings
warnings.filterwarnings('ignore')
#Drop the columns which have been converted to different types:
df.drop(['Item_Type','Outlet_Establishment_Year'],axis=1,inplace=True)  #axis=1(columns) inplace= true makes chages in original dataset:

#Divide into test and train:
train = df.loc[df['source']=="train"] #attribute access a group of rows and columns by label(s) or a boolean array in the given DataFrame.
test = df.loc[df['source']=="test"]

#Drop unnecessary columns:
test.drop(['Item_Outlet_Sales','source'],axis=1,inplace=True)
train.drop(['source'],axis=1,inplace=True)

#Export files as modified versions:
train.to_csv("C:/Users/LENOVO/Desktop/self project/train_modified.csv",index=False)
test.to_csv("C:/Users/LENOVO/Desktop/self project/test_modified.csv",index=False)

# Model Building

In [79]:
# Reading modified data
train2 = pd.read_csv("C:/Users/LENOVO/Desktop/self project/train_modified.csv")
test2 = pd.read_csv("C:/Users/LENOVO/Desktop/self project/test_modified.csv")

In [80]:
X_train = train2.drop(['Item_Outlet_Sales', 'Outlet_Identifier','Item_Identifier'], axis=1)
y_train = train2.Item_Outlet_Sales

In [81]:
X_test = test2.drop(['Outlet_Identifier','Item_Identifier'], axis=1)

In [82]:
y_train

0       3735.1380
1        443.4228
2       2097.2700
3        732.3800
4        994.7052
          ...    
8518    2778.3834
8519     549.2850
8520    1193.1136
8521    1845.5976
8522     765.6700
Name: Item_Outlet_Sales, Length: 8523, dtype: float64

# Linear Regression Model

In [83]:
#Linear Regression Model:
from sklearn.linear_model import  LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [84]:
# Predicting the test set results
y_pred = regressor.predict(X_test)

In [85]:
y_pred

array([1848.53604783, 1472.81670435, 1875.65285894, ..., 1809.18796433,
       3565.6645235 , 1267.46171871])

In [86]:
import warnings
warnings.filterwarnings('ignore')
# Measuring Accuracy
from sklearn.metrics import accuracy_score, r2_score, mean_squared_error
from sklearn.model_selection import cross_val_score
from sklearn import  metrics


In [87]:
from sklearn.model_selection import cross_validate

In [88]:
lr_accuracy = round(regressor.score(X_train,y_train) * 100,2)
lr_accuracy

56.36

In [89]:
r2_score(y_train, regressor.predict(X_train))

0.563589277727048

In [90]:
import warnings
warnings.filterwarnings('ignore')
#Perform cross-validation:
cv_score = cross_val_score(regressor, X_train, y_train, cv=5)


In [91]:
 print(np.sqrt(np.abs(cv_score)))

[0.75571633 0.74509312 0.73995267 0.75255581 0.75171429]


In [92]:
mean_squared_error(y_train, regressor.predict(X_train),squared=False)

1127.2712261909362

In [93]:
submission = pd.DataFrame({
'Item_Identifier':test2['Item_Identifier'],
'Outlet_Identifier':test2['Outlet_Identifier'],
'Item_Outlet_Sales': y_pred
},columns=['Item_Identifier','Outlet_Identifier','Item_Outlet_Sales'])

In [94]:
submission.to_csv('C:/Users/LENOVO/Desktop/self project/sub_LinR.csv',index=False)

# Decision Tree Model:

In [95]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(max_depth=15,min_samples_leaf=300)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=15, min_samples_leaf=300)

In [96]:
y_pred = regressor.predict(X_test)
y_pred

array([1673.98398729, 1349.51290433,  471.30684669, ..., 1892.06614452,
       3805.94860417, 1349.51290433])

In [97]:
tree_accuracy = round(regressor.score(X_train,y_train),2)
tree_accuracy

0.59

In [98]:
r2_score(y_train, regressor.predict(X_train))

0.5884050821570486

In [101]:
import warnings
warnings.filterwarnings('ignore')
cv_score = cross_val_score(regressor, X_train, y_train, cv=5)
print(np.sqrt(np.abs(cv_score)))

[0.76166126 0.74999795 0.72145219 0.75916104 0.75750393]


In [102]:
print("RMSE : %.4g" % np.sqrt(metrics.mean_squared_error(y_train, regressor.predict(X_train))))

RMSE : 1095


In [103]:
submission = pd.DataFrame({
'Item_Identifier':test2['Item_Identifier'],
'Outlet_Identifier':test2['Outlet_Identifier'],
'Item_Outlet_Sales': y_pred
},columns=['Item_Identifier','Outlet_Identifier','Item_Outlet_Sales'])

In [104]:
submission.to_csv('C:/Users/LENOVO/Desktop/self project/sub_DT.csv',index=False)

# Random Forest Regression

In [105]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=100,max_depth=6, min_samples_leaf=50,n_jobs=4)
regressor.fit(X_train, y_train)

RandomForestRegressor(max_depth=6, min_samples_leaf=50, n_jobs=4)

In [106]:
# Predicting the test set results
y_pred = regressor.predict(X_test)
y_pred

array([1649.72039416, 1355.41607811,  592.35490845, ..., 1945.59034199,
       3714.62930764, 1292.79831826])

In [107]:
rf_accuracy = round(regressor.score(X_train,y_train),2)
rf_accuracy

0.61

In [108]:
r2_score(y_train, regressor.predict(X_train))

0.6126532351767466

In [109]:
import warnings
warnings.filterwarnings('ignore')
cv_score = cross_val_score(regressor, X_train, y_train, cv=5)
#print(np.sqrt(np.abs(cv_score)))

In [110]:
print("RMSE : %.4g" % np.sqrt(metrics.mean_squared_error(y_train, regressor.predict(X_train))))

RMSE : 1062


In [111]:
submission = pd.DataFrame({
'Item_Identifier':test2['Item_Identifier'],
'Outlet_Identifier':test2['Outlet_Identifier'],
'Item_Outlet_Sales': y_pred
},columns=['Item_Identifier','Outlet_Identifier','Item_Outlet_Sales'])

In [112]:
submission.to_csv('C:/Users/LENOVO/Desktop/self project/sub_RF.csv',index=False)